### ISSUE TITLE
Doesn't this work with aars?

### ISSUE THREAD

**Issue by izBasit** [oguzbabaoglu/butterfork#5]
Hi,
First of all thank you very much for this library.
So I am using ButterFork in a library module, it works as expected. So now I am going a step further and creating an aar of the library project, but now I get an exception
`java.lang.NoClassDefFoundError: Failed resolution of: Lbutterfork/ButterFork;`

Any insights?

Edit : Had to add the butterfork dependencies to the application project where the aar is being used and it now works.

**Comment by oguzbabaoglu** [comment]
Hello,
Are you referencing your library in your buildscript as `compile "xyz.lib:1.0@aar"`? Because the `@aar` part disables transitive dependencies. 

It is called "artifact only notation" 
see here:
https://docs.gradle.org/current/userguide/dependency_management.html#ssub:artifact_dependencies
> download only the artifact jar, without the dependencies. 

and this SO post:
http://stackoverflow.com/questions/22795455/transitive-dependencies-not-resolved-for-aar-library-using-gradle
```groovy
compile ('com.somepackage:LIBRARY_NAME:1.0.0@aar'){
    transitive=true
}
```

Otherwise it should work as any other library, there is nothing special about it.
